"""EmbodiedGen-compatible USD scene compiler for realistic Kino-Fail episodes.

The first vertical slice is deliberately self-contained: it authors a realistic-scale indoor
workspace from USD-native geometry so the camera/physics/operator pipeline can be reviewed before
the heavyweight EmbodiedGen asset generation is installed.  The manifest calls this source
``kino_authored_fallback`` rather than claiming that the room was generated by EmbodiedGen.  A
future EmbodiedGen ``visual.usd`` can replace the authored visual layer without changing the
collision, physics, operator, camera, or causal logging contracts.

USD imports are local to the compiler functions, keeping scene schemas and audits usable in CPU
unit tests where Isaac Sim is not imported.
"""

from __future__ import annotations

import hashlib
import random
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

from kino_vla.sim.adhesion import IrregularRegion

PrimitiveKind = Literal["cube", "cylinder", "sphere"]


def usd_safe_name(value: str) -> str:
    """Map a human-readable identifier to a deterministic valid USD prim name."""
    encoded = value.replace("+", "_pos_").replace("-", "_neg_").replace(".", "_p_")
    safe = re.sub(r"[^A-Za-z0-9_]", "_", encoded)
    if not safe or safe[0].isdigit():
        safe = f"P_{safe}"
    return safe


@dataclass(frozen=True)
class MaterialSpec:
    name: str
    color: tuple[float, float, float]
    roughness: float = 0.65
    metallic: float = 0.0
    opacity: float = 1.0
    emissive: tuple[float, float, float] = (0.0, 0.0, 0.0)


@dataclass(frozen=True)
class PrimitiveSpec:
    name: str
    kind: PrimitiveKind
    position_xyz: tuple[float, float, float]
    size_xyz: tuple[float, float, float]
    material: str
    collision: bool = False
    semantic_class: str = "background"


@dataclass(frozen=True)
class IndoorSceneSpec:
    scene_id: str
    source_kind: str
    room_extent_xy_m: tuple[float, float]
    ceiling_height_m: float
    materials: tuple[MaterialSpec, ...]
    primitives: tuple[PrimitiveSpec, ...]
    adhesion_region: IrregularRegion
    corridor_y_half_width_m: float = 0.82
    corridor_x_range_m: tuple[float, float] = (-0.4, 6.8)


def build_indoor_adhesion_scene_spec(
    seed: int = 42,
    *,
    scene_id: str = "indoor_workstudio_adhesion_v1",
    source_kind: str = "kino_authored_fallback_embodiedgen_interface_ready",
    film_color: tuple[float, float, float] = (0.84, 0.87, 0.85),
    film_emissive: tuple[float, float, float] = (0.16, 0.18, 0.17),
) -> IndoorSceneSpec:
    """Build the deterministic room, optionally binding it to a frozen corpus scene record."""
    rng = random.Random(seed)
    materials = [
        MaterialSpec("wall_warm", (0.82, 0.80, 0.75), 0.82),
        MaterialSpec("wall_accent", (0.19, 0.25, 0.28), 0.72),
        MaterialSpec("baseboard", (0.12, 0.14, 0.15), 0.55),
        MaterialSpec("oak_light", (0.46, 0.27, 0.13), 0.50),
        MaterialSpec("oak_dark", (0.29, 0.16, 0.08), 0.55),
        MaterialSpec("cabinet", (0.23, 0.27, 0.29), 0.48),
        MaterialSpec("cabinet_face", (0.62, 0.58, 0.48), 0.62),
        MaterialSpec("steel", (0.32, 0.36, 0.38), 0.30, metallic=0.72),
        MaterialSpec("black_matte", (0.035, 0.045, 0.05), 0.78),
        MaterialSpec("ceramic", (0.66, 0.52, 0.38), 0.66),
        MaterialSpec("leaf_dark", (0.07, 0.23, 0.12), 0.90),
        MaterialSpec("leaf_light", (0.13, 0.35, 0.19), 0.88),
        MaterialSpec("rug", (0.20, 0.27, 0.30), 0.95),
        MaterialSpec("crate", (0.38, 0.31, 0.21), 0.82),
        MaterialSpec("glass", (0.32, 0.52, 0.61), 0.12, opacity=0.28),
        MaterialSpec("window_sky", (0.20, 0.42, 0.62), 0.30, emissive=(0.10, 0.22, 0.35)),
        MaterialSpec("door_blue", (0.16, 0.28, 0.34), 0.58),
        MaterialSpec("pegboard", (0.50, 0.39, 0.25), 0.72),
        MaterialSpec("safety_yellow", (0.82, 0.55, 0.07), 0.64),
        MaterialSpec("tool_red", (0.58, 0.08, 0.055), 0.48),
        # Pale protective film stays visually legible under the warm indoor RTX lights without
        # becoming a diagnostic/yellow anomaly marker.
        MaterialSpec(
            "film",
            film_color,
            0.70,
            opacity=1.0,
            emissive=film_emissive,
        ),
        MaterialSpec("film_edge", (0.42, 0.47, 0.45), 0.76, opacity=1.0),
    ]
    primitives: list[PrimitiveSpec] = []

    def add(
        name: str,
        kind: PrimitiveKind,
        pos: tuple[float, float, float],
        size: tuple[float, float, float],
        material: str,
        *,
        collision: bool = False,
        semantic: str = "background",
    ) -> None:
        primitives.append(PrimitiveSpec(name, kind, pos, size, material, collision, semantic))

    # A 10 x 7 m room.  The physical ground remains the known flat Isaac ground while these thin
    # planks form a visual-only finish, preventing coplanar double collision.
    plank_w = 0.145
    for index in range(48):
        y = -3.45 + (index + 0.5) * plank_w
        shade = rng.uniform(-0.035, 0.035)
        mat_name = f"floor_{index:02d}"
        materials.append(
            MaterialSpec(
                mat_name,
                (0.34 + shade, 0.205 + 0.6 * shade, 0.105 + 0.35 * shade),
                0.48 + rng.uniform(-0.05, 0.08),
            )
        )
        # Alternating lengths/offsets create real plank seams instead of a single flat colour.
        for segment in range(3):
            # Slight overlap prevents the hidden Isaac grid from leaking through plank joints.
            length = 3.44 if (index + segment) % 2 == 0 else 3.40
            x = -1.40 + (segment + 0.5) * (10.0 / 3.0)
            x += 0.08 if index % 2 else -0.04
            add(
                f"Floor_Plank_{index:02d}_{segment}",
                "cube",
                (x, y, 0.0035),
                (length, plank_w - 0.006, 0.007),
                mat_name,
                semantic="wood_floor",
            )

    # Architectural shell, baseboards and a charcoal feature wall.
    add("Wall_Left", "cube", (3.4, 3.53, 1.45), (10.0, 0.10, 2.90), "wall_warm", collision=True)
    add("Wall_Right", "cube", (3.4, -3.53, 1.45), (10.0, 0.10, 2.90), "wall_warm", collision=True)
    add("Wall_Far", "cube", (8.42, 0.0, 1.45), (0.10, 7.1, 2.90), "wall_accent", collision=True)
    add("Baseboard_Left", "cube", (3.4, 3.45, 0.07), (10.0, 0.08, 0.14), "baseboard")
    add("Baseboard_Right", "cube", (3.4, -3.45, 0.07), (10.0, 0.08, 0.14), "baseboard")
    add("Baseboard_Far", "cube", (8.34, 0.0, 0.07), (0.08, 7.0, 0.14), "baseboard")

    # The low front camera needs recognizable structure at the end of the traversal.  A utility
    # door and populated tool board turn the far wall into a real work area instead of an empty
    # colour plane.  These are visual/context assets mounted on the wall and never alter the
    # collision corridor or O4 mechanics.
    add(
        "Far_Utility_Door",
        "cube",
        (8.35, -1.72, 1.10),
        (0.035, 1.24, 2.16),
        "door_blue",
        semantic="utility_door",
    )
    for name, pos, size in (
        ("Far_Door_Frame_Left", (8.31, -2.37, 1.10), (0.07, 0.07, 2.28)),
        ("Far_Door_Frame_Right", (8.31, -1.07, 1.10), (0.07, 0.07, 2.28)),
        ("Far_Door_Frame_Top", (8.31, -1.72, 2.22), (0.07, 1.37, 0.07)),
    ):
        add(name, "cube", pos, size, "black_matte", semantic="utility_door")
    add(
        "Far_Door_Handle",
        "cube",
        (8.27, -1.24, 1.06),
        (0.07, 0.22, 0.045),
        "steel",
        semantic="utility_door",
    )
    add(
        "Far_Pegboard",
        "cube",
        (8.34, 1.18, 1.48),
        (0.035, 1.72, 1.18),
        "pegboard",
        semantic="tool_board",
    )
    # A sparse, non-diagnostic set of tools provides parallax and object-scale cues.
    for index, (y, z, sy, sz, material_name) in enumerate(
        (
            (0.63, 1.71, 0.10, 0.58, "steel"),
            (0.91, 1.43, 0.32, 0.09, "tool_red"),
            (1.20, 1.66, 0.12, 0.48, "black_matte"),
            (1.48, 1.35, 0.38, 0.08, "steel"),
            (1.72, 1.72, 0.10, 0.54, "safety_yellow"),
        )
    ):
        add(
            f"Far_Tool_{index}",
            "cube",
            (8.29, y, z),
            (0.055, sy, sz),
            material_name,
            semantic="hand_tool",
        )
    add(
        "Far_Safety_Plate",
        "cube",
        (8.30, 2.55, 1.62),
        (0.045, 0.62, 0.44),
        "safety_yellow",
        semantic="safety_sign",
    )
    add(
        "Far_Safety_Mark",
        "cube",
        (8.26, 2.55, 1.62),
        (0.035, 0.08, 0.30),
        "black_matte",
        semantic="safety_sign",
    )

    # Window bay and frame on the left wall; emissive sky gives the front camera a daylight cue.
    add("Window_Sky", "cube", (4.8, 3.465, 1.78), (2.6, 0.018, 1.25), "window_sky")
    for name, pos, size in (
        ("Window_Frame_Top", (4.8, 3.43, 2.43), (2.75, 0.08, 0.08)),
        ("Window_Frame_Bottom", (4.8, 3.43, 1.13), (2.75, 0.08, 0.08)),
        ("Window_Frame_Left", (3.43, 3.43, 1.78), (0.08, 0.08, 1.38)),
        ("Window_Frame_Right", (6.17, 3.43, 1.78), (0.08, 0.08, 1.38)),
        ("Window_Frame_Mid", (4.8, 3.42, 1.78), (0.055, 0.08, 1.30)),
    ):
        add(name, "cube", pos, size, "black_matte")
    add("Window_Glass", "cube", (4.8, 3.40, 1.78), (2.62, 0.012, 1.24), "glass")

    # Left shelving wall: open shelves, books, plant and storage crates.
    for shelf_x in (0.45, 1.55):
        for side in (-0.44, 0.44):
            add(
                f"Shelf_{shelf_x:.2f}_Side_{side:+.2f}",
                "cube",
                (shelf_x + side, 2.92, 1.02),
                (0.08, 0.46, 2.04),
                "black_matte",
                collision=True,
                semantic="shelving",
            )
        for level in (0.14, 0.62, 1.10, 1.58, 2.02):
            add(
                f"Shelf_{shelf_x:.2f}_Level_{level:.2f}",
                "cube",
                (shelf_x, 2.92, level),
                (0.96, 0.48, 0.055),
                "black_matte",
                collision=True,
                semantic="shelving",
            )
    book_colors = ("cabinet_face", "oak_light", "crate", "wall_accent")
    for index in range(18):
        shelf_x = 0.10 + 0.10 * index if index < 9 else 1.20 + 0.10 * (index - 9)
        level = 0.39 if index % 3 else 0.87
        height = 0.25 + 0.03 * (index % 4)
        add(
            f"Book_{index:02d}",
            "cube",
            (shelf_x, 2.72, level),
            (0.075, 0.20, height),
            book_colors[index % len(book_colors)],
            semantic="book",
        )
    for index, x in enumerate((0.45, 1.55)):
        add(
            f"Crate_{index}",
            "cube",
            (x, 2.88, 1.34),
            (0.62, 0.38, 0.34),
            "crate",
            collision=True,
            semantic="storage_box",
        )

    # Right-side workbench and cabinets leave a >1.6 m central corridor for Go2.
    add(
        "Workbench_Top",
        "cube",
        (2.0, -2.58, 0.82),
        (2.55, 0.78, 0.10),
        "oak_dark",
        collision=True,
        semantic="workbench",
    )
    for x in (0.86, 3.14):
        for y in (-2.88, -2.28):
            add(
                f"Workbench_Leg_{x:.2f}_{y:.2f}",
                "cube",
                (x, y, 0.40),
                (0.09, 0.09, 0.80),
                "steel",
                collision=True,
            )
    for index, x in enumerate((5.25, 6.15, 7.05)):
        add(
            f"Cabinet_{index}",
            "cube",
            (x, -3.00, 0.62),
            (0.82, 0.86, 1.24),
            "cabinet",
            collision=True,
            semantic="cabinet",
        )
        add(
            f"Cabinet_Face_{index}",
            "cube",
            (x, -2.55, 0.62),
            (0.72, 0.035, 1.12),
            "cabinet_face",
            semantic="cabinet",
        )
        add(f"Cabinet_Handle_{index}", "cube", (x, -2.515, 0.77), (0.34, 0.025, 0.035), "steel")

    # A lounge corner and indoor plant make the scene read as a lived-in workspace, not a lab grid.
    add("Rug", "cube", (5.65, 2.10, 0.010), (2.60, 1.65, 0.013), "rug", semantic="rug")
    add(
        "Bench_Seat",
        "cube",
        (6.10, 2.62, 0.42),
        (2.20, 0.72, 0.22),
        "cabinet_face",
        collision=True,
        semantic="bench",
    )
    add(
        "Bench_Back",
        "cube",
        (6.10, 2.96, 0.86),
        (2.20, 0.18, 0.78),
        "cabinet_face",
        collision=True,
        semantic="bench",
    )
    add(
        "Plant_Pot",
        "cylinder",
        (4.15, 2.84, 0.30),
        (0.42, 0.42, 0.60),
        "ceramic",
        collision=True,
        semantic="plant_pot",
    )
    for index, (dx, dy, dz, scale) in enumerate(
        (
            (-0.14, 0.00, 0.78, 0.38),
            (0.13, 0.04, 0.91, 0.33),
            (0.02, -0.09, 1.12, 0.31),
            (-0.20, 0.05, 1.25, 0.26),
            (0.19, -0.04, 1.35, 0.24),
        )
    ):
        add(
            f"Plant_Leaf_{index}",
            "sphere",
            (4.15 + dx, 2.84 + dy, dz),
            (scale, 0.55 * scale, 1.35 * scale),
            "leaf_light" if index % 2 else "leaf_dark",
            semantic="plant",
        )

    # Ceiling baffles/pendants add depth cues without occluding the front camera.
    for index, x in enumerate((0.6, 3.0, 5.4, 7.6)):
        add(f"Ceiling_Baffle_{index}", "cube", (x, 0.0, 2.78), (1.55, 0.075, 0.08), "black_matte")

    adhesion_region = IrregularRegion(
        (
            (2.06, -0.46),
            (2.26, -0.66),
            (2.66, -0.70),
            (2.96, -0.59),
            (3.34, -0.67),
            (3.58, -0.39),
            (3.51, -0.02),
            (3.66, 0.40),
            (3.31, 0.66),
            (2.91, 0.58),
            (2.56, 0.70),
            (2.17, 0.49),
            (2.25, 0.13),
        )
    )
    return IndoorSceneSpec(
        scene_id=scene_id,
        source_kind=source_kind,
        room_extent_xy_m=(10.0, 7.0),
        ceiling_height_m=2.9,
        materials=tuple(materials),
        primitives=tuple(primitives),
        adhesion_region=adhesion_region,
    )


def audit_scene_spec(spec: IndoorSceneSpec) -> dict[str, object]:
    """Run static scene gates before Isaac is launched or a paper artifact is produced."""
    material_names = {material.name for material in spec.materials}
    names = [primitive.name for primitive in spec.primitives]
    duplicate_names = sorted(name for name in set(names) if names.count(name) > 1)
    safe_names = [usd_safe_name(name) for name in names]
    duplicate_safe_names = sorted(name for name in set(safe_names) if safe_names.count(name) > 1)
    missing_materials = sorted(
        {
            primitive.material
            for primitive in spec.primitives
            if primitive.material not in material_names
        }
    )
    xmin, xmax = spec.corridor_x_range_m
    corridor_collisions: list[str] = []
    for primitive in spec.primitives:
        if not primitive.collision:
            continue
        px, py, _ = primitive.position_xyz
        sx, sy, _ = primitive.size_xyz
        overlaps_x = px + sx / 2.0 > xmin and px - sx / 2.0 < xmax
        overlaps_y = abs(py) - sy / 2.0 < spec.corridor_y_half_width_m
        if overlaps_x and overlaps_y:
            corridor_collisions.append(primitive.name)
    ax0, ax1, ay0, ay1 = spec.adhesion_region.bounds
    adhesion_on_corridor = (
        ax1 > xmin
        and ax0 < xmax
        and ay1 > -spec.corridor_y_half_width_m
        and ay0 < spec.corridor_y_half_width_m
    )
    issues = []
    if duplicate_names:
        issues.append("duplicate_primitive_names")
    if duplicate_safe_names:
        issues.append("duplicate_usd_primitive_names")
    if missing_materials:
        issues.append("missing_materials")
    if corridor_collisions:
        issues.append("central_corridor_blocked")
    if not adhesion_on_corridor:
        issues.append("adhesion_outside_route")
    return {
        "passed": not issues,
        "issues": issues,
        "duplicate_names": duplicate_names,
        "duplicate_usd_names": duplicate_safe_names,
        "missing_materials": missing_materials,
        "corridor_collisions": corridor_collisions,
        "adhesion_on_corridor": adhesion_on_corridor,
        "n_primitives": len(spec.primitives),
        "n_collision_primitives": sum(primitive.collision for primitive in spec.primitives),
        "n_materials": len(spec.materials),
        "adhesion_area_m2": abs(spec.adhesion_region.signed_area_m2),
    }


def compile_indoor_scene_layers(spec: IndoorSceneSpec, output_dir: str | Path) -> dict[str, object]:
    """Compile visual/collision/physics/operator layers and a composed episode USDA."""
    from pxr import Gf, Sdf, Usd, UsdGeom, UsdLux, UsdPhysics, UsdShade

    audit = audit_scene_spec(spec)
    if not audit["passed"]:
        raise ValueError(f"scene audit failed: {audit}")
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    def anonymous_stage() -> tuple[Any, Any]:
        layer = Sdf.Layer.CreateAnonymous("kino_scene.usda")
        stage = Usd.Stage.Open(layer)
        root = UsdGeom.Xform.Define(stage, "/IndoorDemo")
        stage.SetDefaultPrim(root.GetPrim())
        return stage, root

    def save(stage: Any, path: Path) -> None:
        if not stage.GetRootLayer().Export(str(path)):
            raise RuntimeError(f"failed to export USD layer {path}")

    def material(stage: Any, root_path: str, value: MaterialSpec) -> Any:
        mat = UsdShade.Material.Define(stage, f"{root_path}/Looks/{value.name}")
        shader = UsdShade.Shader.Define(stage, f"{root_path}/Looks/{value.name}/PBR")
        shader.CreateIdAttr("UsdPreviewSurface")
        shader.CreateInput("diffuseColor", Sdf.ValueTypeNames.Color3f).Set(Gf.Vec3f(*value.color))
        shader.CreateInput("roughness", Sdf.ValueTypeNames.Float).Set(float(value.roughness))
        shader.CreateInput("metallic", Sdf.ValueTypeNames.Float).Set(float(value.metallic))
        shader.CreateInput("opacity", Sdf.ValueTypeNames.Float).Set(float(value.opacity))
        if any(channel > 0.0 for channel in value.emissive):
            shader.CreateInput("emissiveColor", Sdf.ValueTypeNames.Color3f).Set(
                Gf.Vec3f(*value.emissive)
            )
        mat.CreateSurfaceOutput().ConnectToSource(shader.ConnectableAPI(), "surface")
        return mat

    visual_stage, visual_root = anonymous_stage()
    looks = UsdGeom.Scope.Define(visual_stage, "/IndoorDemo/Looks")
    geometry = UsdGeom.Xform.Define(visual_stage, "/IndoorDemo/Geometry")
    del looks, geometry
    material_map = {
        value.name: material(visual_stage, "/IndoorDemo", value) for value in spec.materials
    }
    for primitive in spec.primitives:
        path = f"/IndoorDemo/Geometry/{usd_safe_name(primitive.name)}"
        if primitive.kind == "cube":
            geom = UsdGeom.Cube.Define(visual_stage, path)
            geom.CreateSizeAttr(1.0)
        elif primitive.kind == "cylinder":
            geom = UsdGeom.Cylinder.Define(visual_stage, path)
            geom.CreateRadiusAttr(0.5)
            geom.CreateHeightAttr(1.0)
            geom.CreateAxisAttr("Z")
        elif primitive.kind == "sphere":
            geom = UsdGeom.Sphere.Define(visual_stage, path)
            geom.CreateRadiusAttr(0.5)
        else:  # pragma: no cover - guarded by PrimitiveKind typing
            raise ValueError(f"unsupported primitive kind {primitive.kind}")
        xform = UsdGeom.XformCommonAPI(geom)
        xform.SetTranslate(Gf.Vec3d(*primitive.position_xyz))
        xform.SetScale(Gf.Vec3f(*primitive.size_xyz))
        UsdShade.MaterialBindingAPI.Apply(geom.GetPrim()).Bind(material_map[primitive.material])
        geom.GetPrim().CreateAttribute("kino:semanticClass", Sdf.ValueTypeNames.String).Set(
            primitive.semantic_class
        )
    # The operator's visible asset lives in the visual layer so its PreviewSurface binding stays
    # local and stable under a referenced composition.  Operator semantics/physics remain in the
    # stronger operators.usda layer below.
    film_mat_spec = next(value for value in spec.materials if value.name == "film")
    vertices = spec.adhesion_region.vertices_xy
    film = UsdGeom.Mesh.Define(visual_stage, "/IndoorDemo/Geometry/AdhesiveFilm")
    center_x = sum(x for x, _ in vertices) / len(vertices)
    center_y = sum(y for _, y in vertices) / len(vertices)
    film.CreatePointsAttr(
        [Gf.Vec3f(x, y, 0.009) for x, y in vertices] + [Gf.Vec3f(center_x, center_y, 0.009)]
    )
    # A triangle fan gives RTX unambiguous upward-facing normals; a single concave n-gon can be
    # triangulated differently by USD delegates and appear as an unlit/default-dark surface.
    center_index = len(vertices)
    film.CreateFaceVertexCountsAttr([3] * len(vertices))
    film.CreateFaceVertexIndicesAttr(
        [
            value
            for index in range(len(vertices))
            for value in (center_index, index, (index + 1) % len(vertices))
        ]
    )
    film.CreateNormalsAttr([Gf.Vec3f(0.0, 0.0, 1.0)])
    film.SetNormalsInterpolation("constant")
    film.CreateSubdivisionSchemeAttr("none")
    film.CreateDoubleSidedAttr(True)
    film.CreateDisplayColorAttr([Gf.Vec3f(*film_mat_spec.color)])
    film.CreateDisplayOpacityAttr([float(film_mat_spec.opacity)])
    UsdShade.MaterialBindingAPI.Apply(film.GetPrim()).Bind(material_map["film"])
    film.GetPrim().CreateAttribute("kino:semanticClass", Sdf.ValueTypeNames.String).Set(
        "floor_protective_film"
    )
    # RTX 5.1 renders the referenced concave mesh with a default-dark fallback on this host.  Keep
    # that mesh as the exact machine-readable footprint, but render the same footprint as a set of
    # slightly overlapping thin film panels (well-supported Gprims).  The overlaps also read as
    # realistic laid protective sheets rather than a diagnostic rectangle.
    UsdGeom.Imageable(film.GetPrim()).CreateVisibilityAttr("invisible")
    for index, (x, y, sx, sy, yaw, z) in enumerate(
        (
            (2.84, 0.00, 1.26, 0.88, -2.0, 0.0120),
            (2.25, -0.04, 0.40, 0.68, -7.0, 0.0124),
            (3.44, -0.03, 0.36, 0.64, 7.0, 0.0128),
            (2.82, 0.53, 0.96, 0.22, -3.0, 0.0132),
            (2.83, -0.55, 0.88, 0.21, 4.0, 0.0136),
        )
    ):
        panel = UsdGeom.Cube.Define(visual_stage, f"/IndoorDemo/Geometry/FilmPanel_{index}")
        panel.CreateSizeAttr(1.0)
        panel_xform = UsdGeom.XformCommonAPI(panel)
        panel_xform.SetTranslate(Gf.Vec3d(x, y, z))
        panel_xform.SetRotate(Gf.Vec3f(0.0, 0.0, yaw))
        panel_xform.SetScale(Gf.Vec3f(sx, sy, 0.008))
        UsdShade.MaterialBindingAPI.Apply(panel.GetPrim()).Bind(material_map["film"])
        panel.GetPrim().CreateAttribute("kino:semanticClass", Sdf.ValueTypeNames.String).Set(
            "floor_protective_film"
        )
    # Several non-parallel creases make the film distinct without a diagnostic colour patch.
    for index, (x, y, sx, sy) in enumerate(
        ((2.47, -0.18, 0.78, 0.012), (2.93, 0.31, 0.95, 0.010), (3.27, -0.28, 0.52, 0.014))
    ):
        crease = UsdGeom.Cube.Define(visual_stage, f"/IndoorDemo/Geometry/FilmCrease_{index}")
        crease.CreateSizeAttr(1.0)
        UsdGeom.XformCommonAPI(crease).SetTranslate(Gf.Vec3d(x, y, 0.0178))
        UsdGeom.XformCommonAPI(crease).SetScale(Gf.Vec3f(sx, sy, 0.0015))
        UsdShade.MaterialBindingAPI.Apply(crease.GetPrim()).Bind(material_map["film_edge"])
    # Warm overhead fixtures.  Their visible housings are in Geometry; these lights provide
    # controllable indoor illumination while the window material contributes a daylight cue.
    lights_scope = UsdGeom.Scope.Define(visual_stage, "/IndoorDemo/Lights")
    del lights_scope
    for index, x in enumerate((0.8, 3.2, 5.6, 7.6)):
        light = UsdLux.RectLight.Define(visual_stage, f"/IndoorDemo/Lights/Panel_{index}")
        light.CreateIntensityAttr(450.0)
        light.CreateExposureAttr(7.0)
        light.CreateColorAttr(Gf.Vec3f(1.0, 0.86, 0.72))
        light.CreateWidthAttr(1.30)
        light.CreateHeightAttr(0.12)
        UsdGeom.XformCommonAPI(light).SetTranslate(Gf.Vec3d(x, 0.0, 2.72))
    save(visual_stage, output_dir / "visual.usda")

    collision_stage, collision_root = anonymous_stage()
    del collision_root
    for primitive in spec.primitives:
        if primitive.collision:
            safe_name = usd_safe_name(primitive.name)
            over = collision_stage.OverridePrim(f"/IndoorDemo/Geometry/{safe_name}")
            UsdPhysics.CollisionAPI.Apply(over).CreateCollisionEnabledAttr(True)
    save(collision_stage, output_dir / "collision.usda")

    physics_stage, physics_root = anonymous_stage()
    physics_root.GetPrim().CreateAttribute(
        "kino:groundCollisionSource", Sdf.ValueTypeNames.String
    ).Set("Isaac UnitreeGo2FlatEnv known-flat ground; visual floor is non-colliding")
    physics_root.GetPrim().CreateAttribute(
        "kino:visualCollisionSeparated", Sdf.ValueTypeNames.Bool
    ).Set(True)
    floor_physics = UsdShade.Material.Define(physics_stage, "/IndoorDemo/Physics/FloorMaterial")
    floor_api = UsdPhysics.MaterialAPI.Apply(floor_physics.GetPrim())
    floor_api.CreateStaticFrictionAttr(0.8)
    floor_api.CreateDynamicFrictionAttr(0.6)
    floor_api.CreateRestitutionAttr(0.0)
    save(physics_stage, output_dir / "physics.usda")

    operator_stage, operator_root = anonymous_stage()
    operator_root.GetPrim().CreateAttribute("kino:operator", Sdf.ValueTypeNames.String).Set(
        "O4_tether"
    )
    operator_root.GetPrim().CreateAttribute("kino:subtype", Sdf.ValueTypeNames.String).Set(
        "adhesive_contact"
    )
    operator_root.GetPrim().CreateAttribute("kino:fidelity", Sdf.ValueTypeNames.String).Set(
        "foot_local_force_constraint_v1"
    )
    vertices = spec.adhesion_region.vertices_xy
    film_over = operator_stage.OverridePrim("/IndoorDemo/Geometry/AdhesiveFilm")
    film_over.CreateAttribute("kino:operator", Sdf.ValueTypeNames.String).Set("O4_tether")
    film_over.CreateAttribute("kino:subtype", Sdf.ValueTypeNames.String).Set("adhesive_contact")
    film_over.CreateAttribute("kino:footprintXY", Sdf.ValueTypeNames.Float2Array).Set(
        [Gf.Vec2f(x, y) for x, y in vertices]
    )
    save(operator_stage, output_dir / "operators.usda")

    episode_stage, episode_root = anonymous_stage()
    episode_root.GetPrim().CreateAttribute("kino:sceneId", Sdf.ValueTypeNames.String).Set(
        spec.scene_id
    )
    episode_root.GetPrim().CreateAttribute("kino:sourceKind", Sdf.ValueTypeNames.String).Set(
        spec.source_kind
    )
    episode_stage.GetRootLayer().subLayerPaths = [
        "operators.usda",
        "physics.usda",
        "collision.usda",
        "visual.usda",
    ]
    save(episode_stage, output_dir / "episode.usda")

    layer_names = (
        "visual.usda",
        "collision.usda",
        "physics.usda",
        "operators.usda",
        "episode.usda",
    )
    hashes = {
        name: hashlib.sha256((output_dir / name).read_bytes()).hexdigest() for name in layer_names
    }
    return {
        "scene_id": spec.scene_id,
        "source_kind": spec.source_kind,
        "output_dir": str(output_dir),
        "episode_usd": str(output_dir / "episode.usda"),
        "layers": list(layer_names),
        "sha256": hashes,
        "audit": audit,
    }
